### ISSUE TITLE
目前遇到的问题

### ISSUE THREAD

**Issue by Zyx-lang** [mbarbierato/Lenovo-Miix720#2]
这个EFI已经接近完美了，触控板确实无法驱动，还有一个小问题是会无限睡眠-唤醒循环，不知道是不是因为我装的是10.15.7版本的原因。

**Comment by Zyx-lang** [comment]
经过多次尝试，睡眠-唤醒循环不是每次都会出现

**Comment by mbarbierato** [comment]
write in english please
